### ISSUE TITLE
关于这个 SDK 集成

### ISSUE THREAD

**Issue by Agoines** [richtap-haptics/RichTapDynamics#1]
您好，打扰一下，是否能在自己的应用或者库中集成这个 SDK？如果可以集成，对应用或者库有什么要求吗？

**Comment by RichTapHaptics** [comment]
> 您好，打扰一下，是否能在自己的应用或者库中集成这个 SDK？如果可以集成，对应用或者库有什么要求吗？

可以的。我们的SDK分免费版和完整版。RichTapDynamics项目中带的是免费版（在app/libs/ 目录内），可以集成到任意App中去。
为了确保振动品质，我们要求Android 8.0及以上系统。

**Comment by Agoines** [comment]
感谢解答

RichTape-coder ***@***.***> 于 2022年5月12日周四 下午4:00写道：
